var React = require('react');

var ColophonModal = React.createClass({
  render: function () {
    return (
      <div className="modal colophon">
        <div className="modal-content">
          <div className="modal-header">
            <button className="close" onClick={this.props.controller.hideModal}>Close</button>
          </div>
          <h3>Colophon</h3>
          <h4>Fonts</h4>
          <p>
            Fonts being used are <a href="https://www.google.com/fonts/specimen/Vollkorn">Vollkorn</a> and <a href="https://www.google.com/fonts/specimen/Old+Standard+TT">Old Standard TT</a>.
          </p>
          <h4>Web Technologies</h4>
          <p>
            The site is generated by Jekyll.
            All styling (using SCSS) is 100% bespoke for this site. No Bootstrap here!
            Interactive goodies are powered by React.
            Peruse the source code on <a href="https://github.com/ktbartholomew/raedcabello.com">GitHub</a>.
          </p>
          <h4>Credits</h4>
          <p>
            Design: <a href="https://twitter.com/raedcabello">Rae D. Cabello</a> <br />
            Development: <a href="https://github.com/ktbartholomew">Keith Bartholomew</a>
          </p>
          <h4>Etc.</h4>
          <p>
            I plan on adding more to this site (like a proper portfolio) when I’m not so busy.
          </p>
        </div>
      </div>
    );
  }
});

module.exports = ColophonModal;
