var React = require('react');

var ModalState = require('../states/modal');

var ColophonLink = React.createClass({
  hideModal: function (e) {
    e.preventDefault();
    ModalState.hide();
  },
  showModal: function (e) {
    e.preventDefault();
    ModalState.show((
      <div className="modal colophon" key="contactForm">
        <div className="modal-content">
          <div className="modal-header">
            <button className="close" onClick={this.hideModal}>Close</button>
          </div>
          <h3>Colophon</h3>
          <h4>Fonts</h4>
          <p>
            Headings and certain links use <a href="https://www.google.com/fonts/specimen/Old+Standard+TT">Old Standard TT</a>. Most body copy uses <a href="https://www.google.com/fonts/specimen/Vollkorn">Vollkorn</a>.
          </p>
          <h4>Technology</h4>
          <p>
            The site is generated by Jekyll.
            All styling (using SCSS) is 100% bespoke for this site. No Bootstrap here!
            Interactive goodies are powered by React.
            Peruse the source code on <a href="https://github.com/ktbartholomew/raedcabello.com">GitHub</a>.
          </p>
          <h4>Credits</h4>
          <p>
            Designed by <a href="https://twitter.com/raedcabello">Rae D. Cabello</a>. <br />
            Developed by <a href="https://github.com/ktbartholomew">Keith Bartholomew</a>.
          </p>
          <h4>Etc.</h4>
          <p>
            I plan on adding more to the site (like a portfolio) when I’m not so busy.
          </p>
        </div>
      </div>
    ));
  },
  render: function () {
    return (<span onClick={this.showModal}>&amp;</span>);
  }
});

module.exports = ColophonLink;
