#!/bin/bash

curl -sL -o /tmp/rack-1.1.1 https://ec4a542dbf90c03b9f75-b342aba65414ad802720b41e8159cf45.ssl.cf5.rackcdn.com/1.1.1/Linux/amd64/rack
chmod u+x /tmp/rack-1.1.1

export RS_USERNAME=${RACKSPACE_USERNAME}
export RS_API_KEY=${RACKSPACE_APIKEY}
export RS_REGION_NAME=${CF_REGION:-DFW}
container=${CF_CONTAINER}

alias rack="/tmp/rack-1.1.1"

jekyll build

files=$(find _site -type f)

for file in ${files}; do
  objname=$(echo ${file} | sed s/_site\\///)
  rack files object upload --container ${container} --name ${objname} --file ${file}
done
